;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        abort-recursive-edit
        ace-jump-move
        backward-delete-char
        backward-delete-word
        delete-current-line
        delete-region
        god-mode-self-insert
        helm-confirm-and-exit-minibuffer
        helm-mini
        hydra-git/body
        hydra-git/elpy-nav-indent-shift-left
        hydra-git/elpy-nav-indent-shift-right
        hydra-git/elpy-nav-move-line-or-region-down
        hydra-git/flycheck-next-error
        hydra-git/flycheck-previous-error
        ido-switch-buffer
        indent-for-tab-command
        keyboard-quit
        kill-region
        my-delete-whole-line
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        org-yank
        ryo:6c0b5bec3522d2e495ff80ad83791864:insert-quotes
        ryo:d77df2a102a270b1c4ab1b70c78e1fd0:insert\ text
        ryo:d80a40411c8db939213101425d5bc549:Comment
        slime-autodoc-space
        slime-space
        smarter-move-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-done
        ace-jump-move
        ace-mc-add-char
        ace-mc-add-multiple-cursors
        ace-mc-add-single-cursor
        ace-mc-do-keyboard-reset
        ace-mc-quick-exchange
        beginning-of-buffer
        god-mode-all
        helm-M-x
        hydra-git/nil
        jupyter-eval-buffer
        point-to-register
        ryo-modal-global-mode
        ryo-modal-mode-all
        ))
